version: "3.5"
services:
  server:
    image: urecommendme/backend
    container_name: "recomendador_backend"
    depends_on:
      - db
    ports:
      - "8080:80"
    networks:
      - backend
  db:
    image: mongo:3.6
    container_name: "recomendador_db"
    restart: always
    networks:
      - backend
    volumes:
      - ./database/init-data:/data/init-data
      - ./database/scripts:/docker-entrypoint-initdb.d
    ports:
      - "27017:27017"

networks:
  backend:
    name: "recomendador_network"
