services:
        server:
                build: ./backend
                container_name: "recomendador_backend"
                ports:
                        - "80:80"
                networks:
                        - backend
        db:
                image: mongo:3.6
                container_name: "recomendador_db"
                restart: always
                networks:
                        - backend
networks:
        backend:
                name: "recomendador_network"
