version: "3.5"
services:
  reverse-proxy:
    image: nginx:1.17.10
    container_name: reverseproxy
    depends_on:
      - db
      - server
    volumes:
       - ./nginx-conf/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"

  db:
    image: mongo:3.6
    container_name: "recomendador_db"
    restart: always
    networks:
      - backend
    volumes:
      - ./database/init-data:/data/init-data
      - ./database/scripts:/docker-entrypoint-initdb.d

  server:
    build:
      context: "./backend"
      dockerfile: "Dockerfile"
    container_name: "recomendador_backend"
    depends_on:
      - db
    ports:
      - "3000"
    networks:
      - backend

networks:
  backend:
    name: "recomendador_network"
