name: Deploy app

on:
  push:
    branches:
      - test-media

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to droplet using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          debug: true
          script: |
                    cd fs5-recomendador-backend/
                    git clone https://github.com/fullstacktf/fs5-recomendador-backend.git
                    docker stop recomendador_backend
                    docker container rm recomendador_backend
                    docker rmi fs5-recomendador-backend_server
                    docker stop recomendador_db
                    docker container rm recomendador_db
                    docker rmi fs5-recomendador-backend_db
                    docker-compose up -d
  