name: Deploy app

on:
  push:
    branches:
      - test-media

jobs:
  build_image_and_push:
    name: Build and push image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: urecommendme/backend

  update_dockerhub_image:
    needs: build_image_and_push
    name: Deploy the new image for backend in the server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
    
      - name: copy docker-compose.yml file
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: "./docker-compose.yml"
          target: "docker-compose-back"

      - name: copy database
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: "./database"
          target: "docker-compose-back"

  execute-docker-compose-droplet:
    runs-on: ubuntu-latest
    needs: update_dockerhub_image

    steps:
      - name: Run docker-compose SSH command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
                    cd docker-compose-back
                    docker stop recomendador_backend
                    docker container rm recomendador_backend
                    docker rmi urecommendme/backend
                    docker stop recomendador_db
                    docker container rm recomendador_db
                    docker rmi mongo:3.6
                    docker-compose up -d
